// fastconfgen reads a YAML or JSON configuration sample and emits an
// equivalent Go struct definition. Pragmatic
// YAML-by-example codegen with no external deps beyond yaml.v3.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"sort"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

// version is injected at build time via `-ldflags "-X main.version=<tag>"`
// by the dist pipeline. Default "dev" is reported when building from source
// without -ldflags (e.g. `go install`).
var version = "dev"

func main() {
	in := flag.String("in", "", "input YAML/JSON file (default stdin)")
	out := flag.String("out", "", "output .go file (default stdout)")
	pkg := flag.String("pkg", "config", "Go package name")
	typ := flag.String("type", "Config", "root struct name")
	showVersion := flag.Bool("version", false, "print version and exit")
	flag.Parse()

	if *showVersion {
		fmt.Printf("fastconfgen %s\n", version)
		return
	}

	var src []byte
	var err error
	if *in == "" {
		src, err = io.ReadAll(os.Stdin)
	} else {
		src, err = os.ReadFile(*in)
	}
	if err != nil {
		die(err)
	}
	var root map[string]any
	if err := yaml.Unmarshal(src, &root); err != nil {
		die(fmt.Errorf("parse: %w", err))
	}
	srcOut, err := renderSource(*pkg, *typ, root)
	if err != nil {
		die(err)
	}
	if *out == "" {
		_, _ = os.Stdout.Write(srcOut)
	} else if err := os.WriteFile(*out, srcOut, 0o644); err != nil {
		die(err)
	}
}

func renderSource(pkg, typ string, root map[string]any) ([]byte, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by fastconfgen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	emit(&b, typ, root)
	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return out, nil
}

func die(err error) {
	fmt.Fprintln(os.Stderr, "fastconfgen:", err)
	os.Exit(1)
}

type nested struct {
	name string
	val  map[string]any
}

var anySample = &struct{}{}

func emit(w *strings.Builder, name string, m map[string]any) {
	e := &emitter{usedTypes: map[string]int{name: 1}}
	e.emitStruct(w, name, m)
}

type emitter struct {
	usedTypes map[string]int
}

func (e *emitter) emitStruct(w *strings.Builder, name string, m map[string]any) {
	type field struct {
		name, typ, tag string
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var nests []nested
	fields := make([]field, 0, len(keys))
	usedFields := map[string]int{}
	for _, k := range keys {
		v := m[k]
		fname := uniqueExportName(k, usedFields)
		ftype := e.fieldType(name+fname, v, &nests)
		// Escape any backticks in the key to avoid breaking the raw-string
		// literal that wraps the generated struct tag.
		safeK := strings.ReplaceAll(k, "`", "`+\"`\"+`")
		fields = append(fields, field{fname, ftype, fmt.Sprintf("`yaml:%q json:%q`", safeK, safeK)})
	}
	fmt.Fprintf(w, "type %s struct {\n", name)
	for _, f := range fields {
		fmt.Fprintf(w, "\t%s %s %s\n", f.name, f.typ, f.tag)
	}
	fmt.Fprintf(w, "}\n\n")
	for _, n := range nests {
		e.emitStruct(w, n.name, n.val)
	}
}

func (e *emitter) fieldType(typeHint string, v any, nests *[]nested) string {
	switch tv := v.(type) {
	case map[string]any:
		name := e.uniqueTypeName(typeHint)
		*nests = append(*nests, nested{name, tv})
		return name
	case []any:
		return "[]" + e.sliceElemType(typeHint, tv, nests)
	default:
		return scalarType(tv)
	}
}

func (e *emitter) sliceElemType(typeHint string, s []any, nests *[]nested) string {
	var scalar string
	var object map[string]any
	for _, v := range s {
		if v == nil {
			continue
		}
		if m, ok := v.(map[string]any); ok {
			if scalar != "" {
				return "any"
			}
			if object == nil {
				object = map[string]any{}
			}
			mergeSampleMap(object, m)
			continue
		}
		typ := scalarType(v)
		if typ == "any" || object != nil {
			return "any"
		}
		scalar = mergeScalarType(scalar, typ)
		if scalar == "any" {
			return "any"
		}
	}
	if object != nil {
		sub := e.uniqueTypeName(typeHint + "Item")
		*nests = append(*nests, nested{sub, object})
		return sub
	}
	if scalar != "" {
		return scalar
	}
	return "any"
}

func (e *emitter) uniqueTypeName(base string) string {
	e.usedTypes[base]++
	if e.usedTypes[base] == 1 {
		return base
	}
	return fmt.Sprintf("%s%d", base, e.usedTypes[base])
}

func mergeSampleMap(dst, src map[string]any) {
	for k, v := range src {
		if old, ok := dst[k]; ok {
			dst[k] = mergeSampleValue(old, v)
			continue
		}
		dst[k] = v
	}
}

func mergeSampleValue(a, b any) any {
	if a == anySample || b == anySample {
		return anySample
	}
	if a == nil {
		return b
	}
	if b == nil {
		return a
	}
	am, aok := a.(map[string]any)
	bm, bok := b.(map[string]any)
	if aok && bok {
		out := cloneSampleMap(am)
		mergeSampleMap(out, bm)
		return out
	}
	if aok || bok {
		return anySample
	}
	as, aok := a.([]any)
	bs, bok := b.([]any)
	if aok && bok {
		return append(append([]any(nil), as...), bs...)
	}
	if aok || bok {
		return anySample
	}
	typ := mergeScalarType(scalarType(a), scalarType(b))
	switch typ {
	case "string":
		return ""
	case "bool":
		return false
	case "int64":
		return int64(0)
	case "float64":
		return float64(0)
	default:
		return anySample
	}
}

func cloneSampleMap(in map[string]any) map[string]any {
	out := make(map[string]any, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}

func scalarType(v any) string {
	switch v.(type) {
	case string:
		return "string"
	case bool:
		return "bool"
	case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64:
		return "int64"
	case float32, float64:
		return "float64"
	case nil:
		return "any"
	default:
		return "any"
	}
}

func mergeScalarType(a, b string) string {
	if a == "" {
		return b
	}
	if a == b {
		return a
	}
	if (a == "int64" && b == "float64") || (a == "float64" && b == "int64") {
		return "float64"
	}
	return "any"
}

func uniqueExportName(k string, used map[string]int) string {
	base := exportName(k)
	used[base]++
	if used[base] == 1 {
		return base
	}
	return fmt.Sprintf("%s%d", base, used[base])
}

func exportName(k string) string {
	parts := splitIdent(k)
	for i, p := range parts {
		if up, ok := initialisms[strings.ToLower(p)]; ok {
			parts[i] = up
		} else {
			parts[i] = capitalize(p)
		}
	}
	out := strings.Join(parts, "")
	if out == "" {
		return "Field"
	}
	if !unicode.IsLetter(rune(out[0])) {
		out = "F" + out
	}
	return out
}

func splitIdent(s string) []string {
	var out []string
	cur := strings.Builder{}
	for _, r := range s {
		if r == '_' || r == '-' || r == '.' || r == ' ' {
			if cur.Len() > 0 {
				out = append(out, cur.String())
				cur.Reset()
			}
			continue
		}
		cur.WriteRune(r)
	}
	if cur.Len() > 0 {
		out = append(out, cur.String())
	}
	return out
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

var initialisms = map[string]string{
	"id": "ID", "url": "URL", "uri": "URI", "http": "HTTP", "https": "HTTPS",
	"api": "API", "ip": "IP", "tcp": "TCP", "udp": "UDP", "tls": "TLS",
	"sql": "SQL", "json": "JSON", "yaml": "YAML", "uuid": "UUID", "db": "DB",
}
