// fastconfgen reads a YAML or JSON configuration sample and emits an
// equivalent Go struct definition. Phase 27 — pragmatic
// YAML-by-example codegen with no external deps beyond yaml.v3.
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

// version is injected at build time via `-ldflags "-X main.version=<tag>"`
// by the dist pipeline. Default "dev" is reported when building from source
// without -ldflags (e.g. `go install`).
var version = "dev"

func main() {
	in := flag.String("in", "", "input YAML/JSON file (default stdin)")
	out := flag.String("out", "", "output .go file (default stdout)")
	pkg := flag.String("pkg", "config", "Go package name")
	typ := flag.String("type", "Config", "root struct name")
	showVersion := flag.Bool("version", false, "print version and exit")
	flag.Parse()

	if *showVersion {
		fmt.Printf("fastconfgen %s\n", version)
		return
	}

	var src []byte
	var err error
	if *in == "" {
		src, err = io.ReadAll(os.Stdin)
	} else {
		src, err = os.ReadFile(*in)
	}
	if err != nil {
		die(err)
	}
	var root map[string]any
	if err := yaml.Unmarshal(src, &root); err != nil {
		die(fmt.Errorf("parse: %w", err))
	}
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by fastconfgen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", *pkg)
	emit(&b, *typ, root)
	if *out == "" {
		_, _ = os.Stdout.Write([]byte(b.String()))
	} else if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		die(err)
	}
}

func die(err error) {
	fmt.Fprintln(os.Stderr, "fastconfgen:", err)
	os.Exit(1)
}

type nested struct {
	name string
	val  map[string]any
}

func emit(w *strings.Builder, name string, m map[string]any) {
	type field struct {
		name, typ, tag string
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var nests []nested
	fields := make([]field, 0, len(keys))
	for _, k := range keys {
		v := m[k]
		fname := exportName(k)
		var ftype string
		switch tv := v.(type) {
		case map[string]any:
			sub := name + fname
			ftype = sub
			nests = append(nests, nested{sub, tv})
		case []any:
			ftype = "[]" + sliceElemType(name+fname, tv, &nests)
		case string:
			ftype = "string"
		case bool:
			ftype = "bool"
		case int, int64:
			ftype = "int64"
		case float64:
			ftype = "float64"
		case nil:
			ftype = "any"
		default:
			ftype = "any"
		}
		fields = append(fields, field{fname, ftype, fmt.Sprintf("`yaml:%q json:%q`", k, k)})
	}
	fmt.Fprintf(w, "type %s struct {\n", name)
	for _, f := range fields {
		fmt.Fprintf(w, "\t%s %s %s\n", f.name, f.typ, f.tag)
	}
	fmt.Fprintf(w, "}\n\n")
	for _, n := range nests {
		emit(w, n.name, n.val)
	}
}

func sliceElemType(typeHint string, s []any, nests *[]nested) string {
	if len(s) == 0 {
		return "any"
	}
	switch fv := s[0].(type) {
	case map[string]any:
		sub := typeHint + "Item"
		*nests = append(*nests, nested{sub, fv})
		return sub
	case string:
		return "string"
	case bool:
		return "bool"
	case int, int64:
		return "int64"
	case float64:
		return "float64"
	}
	return "any"
}

func exportName(k string) string {
	parts := splitIdent(k)
	for i, p := range parts {
		if up, ok := initialisms[strings.ToLower(p)]; ok {
			parts[i] = up
		} else {
			parts[i] = capitalize(p)
		}
	}
	out := strings.Join(parts, "")
	if out == "" {
		return "Field"
	}
	if !unicode.IsLetter(rune(out[0])) {
		out = "F" + out
	}
	return out
}

func splitIdent(s string) []string {
	var out []string
	cur := strings.Builder{}
	for _, r := range s {
		if r == '_' || r == '-' || r == '.' || r == ' ' {
			if cur.Len() > 0 {
				out = append(out, cur.String())
				cur.Reset()
			}
			continue
		}
		cur.WriteRune(r)
	}
	if cur.Len() > 0 {
		out = append(out, cur.String())
	}
	return out
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

var initialisms = map[string]string{
	"id": "ID", "url": "URL", "uri": "URI", "http": "HTTP", "https": "HTTPS",
	"api": "API", "ip": "IP", "tcp": "TCP", "udp": "UDP", "tls": "TLS",
	"sql": "SQL", "json": "JSON", "yaml": "YAML", "uuid": "UUID", "db": "DB",
}
