// api-snapshot emits a stable, text representation of the root
// fastconf package's exported declarations. It intentionally uses only
// the standard library so it can run in the lower-bound Go toolchain.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type apiEntry struct {
	key  string
	text string
}

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	entries, err := snapshot(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "api-snapshot:", err)
		os.Exit(1)
	}
	fmt.Println("# fastconf root exported API snapshot")
	fmt.Println("# generated by: go run ./tools/api-snapshot")
	for _, e := range entries {
		fmt.Println()
		fmt.Println(e.text)
	}
}

func snapshot(root string) ([]apiEntry, error) {
	fset := token.NewFileSet()
	files, err := filepath.Glob(filepath.Join(root, "*.go"))
	if err != nil {
		return nil, err
	}
	var entries []apiEntry
	for _, path := range files {
		if strings.HasSuffix(path, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return nil, err
		}
		if f.Name.Name != "fastconf" {
			continue
		}
		for _, decl := range f.Decls {
			switch d := decl.(type) {
			case *ast.GenDecl:
				entries = append(entries, genEntries(fset, d)...)
			case *ast.FuncDecl:
				if e, ok := funcEntry(fset, d); ok {
					entries = append(entries, e)
				}
			}
		}
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].key < entries[j].key })
	return entries, nil
}

func genEntries(fset *token.FileSet, d *ast.GenDecl) []apiEntry {
	var out []apiEntry
	switch d.Tok {
	case token.TYPE:
		for _, spec := range d.Specs {
			ts := spec.(*ast.TypeSpec)
			if !ts.Name.IsExported() {
				continue
			}
			out = append(out, apiEntry{
				key:  "type:" + ts.Name.Name,
				text: nodeString(fset, ts),
			})
		}
	case token.CONST, token.VAR:
		for _, spec := range d.Specs {
			vs := spec.(*ast.ValueSpec)
			for i, name := range vs.Names {
				if !name.IsExported() {
					continue
				}
				out = append(out, apiEntry{
					key:  strings.ToLower(d.Tok.String()) + ":" + name.Name,
					text: valueSpecString(fset, d.Tok, vs, i),
				})
			}
		}
	}
	return out
}

func funcEntry(fset *token.FileSet, d *ast.FuncDecl) (apiEntry, bool) {
	if !d.Name.IsExported() {
		return apiEntry{}, false
	}
	copy := *d
	copy.Body = nil
	if d.Recv == nil {
		return apiEntry{key: "func:" + d.Name.Name, text: nodeString(fset, &copy)}, true
	}
	recv := receiverName(d.Recv)
	if recv == "" || !ast.IsExported(recv) {
		return apiEntry{}, false
	}
	return apiEntry{
		key:  "method:" + recv + "." + d.Name.Name,
		text: nodeString(fset, &copy),
	}, true
}

func receiverName(recv *ast.FieldList) string {
	if recv == nil || len(recv.List) == 0 {
		return ""
	}
	expr := recv.List[0].Type
	for {
		switch t := expr.(type) {
		case *ast.StarExpr:
			expr = t.X
		case *ast.IndexExpr:
			expr = t.X
		case *ast.IndexListExpr:
			expr = t.X
		case *ast.Ident:
			return t.Name
		default:
			return ""
		}
	}
}

func valueSpecString(fset *token.FileSet, tok token.Token, vs *ast.ValueSpec, i int) string {
	var b strings.Builder
	b.WriteString(tok.String())
	b.WriteByte(' ')
	b.WriteString(vs.Names[i].Name)
	if vs.Type != nil {
		b.WriteByte(' ')
		b.WriteString(nodeString(fset, vs.Type))
	}
	if i < len(vs.Values) {
		b.WriteString(" = ")
		b.WriteString(nodeString(fset, vs.Values[i]))
	}
	return b.String()
}

func nodeString(fset *token.FileSet, n any) string {
	var b bytes.Buffer
	_ = (&printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 8}).Fprint(&b, fset, n)
	return strings.TrimSpace(b.String())
}
